### ISSUE TITLE
More highlighting please

### ISSUE THREAD

**Issue by uduse** [joneshf/sublime-zimpl#1]
Here're the features that I think will be awesome to add:
- Color symbols in {} and <>  as the same color as those in []. I only see colors in [] right now, and it's weird. ( de-color all of them works)
- say we have "subto constraint_x"then"subto"should have a different color from"constraint_x"
- comments should have a different color, I prefer gray or other dimmed colors.

**Comment by joneshf** [comment]
I didn't think anyone was actually using this. :) I've got no real incentive to work on this at the moment, so it might be a couple days to a few weeks until I get around to it. But PR's are always accepted.

I'll raise some issues to remind myself.
- [ ] I think that can be done pretty easily.
- [ ] That's currently how it is. It might not show up as different depending on which color scheme you use. I know Monokai has quite a few different scopes with the same color.
- [ ] This sounds like a bug. They should be the standard comment color.

**Comment by uduse** [comment]
A quick question: were you in MAT 168?

**Comment by joneshf** [comment]
Yep! That was a boat load of work. Fun, but a lot of work.

**Comment by uduse** [comment]
Yes agree. BTW, I am working for the professor right now, and we are having more fun but laborious work D:

**Comment by joneshf** [comment]
Oh yeah? That's pretty cool. What sorts of thkngs are you doing now?

**Comment by uduse** [comment]
Just messing around an open source project called Sage... changing notations, making interfaces, e.t.c.

**Comment by uduse** [comment]
Closed due to inactivity.
